added integration tests.
Kuunika/dhis2-fail-queue-worker pull request #3
Opened 2019-05-03 07:00 UTC by Mmalumbo

Signed-off-by: mmalumbo <mmalumbo@gmail.com>

2019-05-30 06:10 UTC, liwoo requested changes

2019-05-30 06:10 UTC, liwoo commented on src/tests/failqueue.test.ts
> +    expect(testMigrationDataElement.createdAt).toBeTruthy();
assertions should be more explicit, like assert against an actual date time

2019-05-30 06:10 UTC, liwoo commented on src/tests/fixtures/database.fixture.ts
> +export const malu = 'maliu';
don't understand this...

2019-05-30 06:10 UTC, liwoo commented on src/tests/failqueue.test.ts
> +  it('should failt to send data elements that failed migration to dhis2', async () => {
we need to find a way of testing the number of retries...

2019-06-03 08:06 UTC, Mmalumbo commented on src/tests/failqueue.test.ts
> +let path: string;
changed it to const.

2019-06-03 08:07 UTC, Mmalumbo commented on src/tests/failqueue.test.ts
> +describe('', () => {
added a name.

2021-10-19 07:31 UTC, Mmalumbo commented
ooo

2021-10-19 07:31 UTC, closed without merging